### ISSUE TITLE
Improvment for managing queue timeout of players

### ISSUE THREAD

**Issue by oredin** [Conbonbot/RS-Club-Bot#5]
Hi,

I just looked a little into the problem of queue timeout.

You could try to modify the sql query on the line below.
https://github.com/Conbonbot/RS-Club-Bot/blob/3d16a9882b60103adeb6ea9458a72cbe61a8e25f/routines/cogs/queue.py#L140

I would suggest something like :
```SELECT time, length, user_id, level, channel_id FROM main where ((strftime('%s', 'now') - time) / 60) >= length;```

With the added `WHERE` clause, you should retrieve only the players who are timed out instead of retrieving all the queued players.
Since I didn't install the bot, I couldn't test it but with a little tweaking, it should work fine !

Hope this helps.

Cheers !

**Comment by connorharv** [comment]
Unfortunately this wouldn't solve the issue, while this certainly is faster and I probably should have used it (when I fix it, I'll definitely use that instead of what was originally written). The issue is with the database itself, I was dumb and thought SQLite3 could support 500+ people without any issues, turns out it really can't, and almost every time it calls that execute statement the database is locked and the command fails without pinging/removing any players. I am working on using PostgreSQL instead of SQLite3 so it'll be much faster, but I'm not too proficient in PostgreSQL so it'll take some time.

**Comment by oredin** [comment]
If you need some help, ping me. I'll need to setup a dev environment but it shouldn't take me more than a day or so before I can fork the project and help you make some change to migrate to Postgresql.
